### PR TITLE
QCNN Multi-worker tutorial

### PR DESCRIPTION
**Pull request by verult**
A tutorial for training a QCNN using multiple workers on top of Kubernetes and Google Cloud.

@MichaelBroughton

### CODE REVIEW

**Comment by MichaelBroughton** [comment]
@lamberta I was thinking for this tutorial it might make sense to put all of these files into the `/research` branch and then create a `.ipynb` notebook with a little more explanation (to go along with the Blog post) that what is inside the REAMDE file that we feature in `/docs/tutorials`. What do you think ?

**Comment by verult** [comment]
Most of the stuff to run in the README are shell commands rather than Python code. Would that be a good fit for an `.ipynb`?

**Comment by lamberta** [comment]
Yeah, this is not the place for Dockerfiles, Makefiles, and Python files—these can't be published as docs on the https://tensorflow.org/quantum website.

This kind of thing is normally what we use the [tensorflow/examples](https://github.com/tensorflow/examples) repo for. And some projects, like TFP, keep a separate [/examples](https://github.com/tensorflow/probability/tree/master/tensorflow_probability/examples) directory (just don't put it in the `/docs` directory). But these are all *maintained* examples—if it goes into the `master` branch, expect PRs for it. If it's for a blog post and not an official example, then creating a separate `research` branch makes sense.

**Comment by verult** [comment]
Got it. The intention is indeed to maintain this example and update this in the future, as improvements in Kubernetes will make the recommended best practice change in the next few months. @MichaelBroughton what do you think about creating an `example/` directory in the TFQ repo, or should this be part of `tensorflow/examples`?

**Comment by MichaelBroughton** [comment]
After doing some thinking on this I think it would be best for now (ant probably the easiest too) to place this PR into the`research` branch as a new directory. That way we can link to it in the blog post and refer any interested users etc. There are links to the research branch in places like the whitepaper and the original launch post so I think it makes a lot of sense.

**Comment by MichaelBroughton** [comment]
Merged #574 so we are safe to close this.

**Pull request closed without merging**
