### PR TITLE
Fix typo in the docstring of Differentiator.differentiate_analytic

### PR DESCRIPTION
**Pull request by majafranz**
# Changes

Fixed a typo in the `differentiator.Differentiator.differentiate_analytic` docstring.
"... calls he inheriting ..." got changed into "... calls the inheriting ..."

### CODE REVIEW

**Comment by mhucka** [comment]
@majafranz Thanks for catching this. I'd be happy to merge it, but (as silly as it seems for such a small pull request) we are required to get a contributor license agreement from all contributors before we can accept contributions. Would you be willing and able to fill out the CLA form? (See the bot's comment higher ↑ on this page.)

**Comment by majafranz** [comment]
> @majafranz Thanks for catching this. I'd be happy to merge it, but (as silly as it seems for such a small pull request) we are required to get a contributor license agreement from all contributors before we can accept contributions. Would you be willing and able to fill out the CLA form? (See the bot's comment higher ↑ on this page.)

Hi, I think I have already filled in the form. Maybe it needs to be checked again?
Anyway, as this PR only fixes a typo, I would not be too upset if it was not merged :)

**Comment by mhucka** [comment]
> Hi, I think I have already filled in the form. Maybe it needs to be checked again?

Thanks for letting me know. I re-ran the check and it passed this time!

**Review by mhucka — APPROVED** [review]
LGTM.

**Pull request merged**
