### PR TITLE
Updated install instructions for new TF and Bazel versions

### PR DESCRIPTION
**Pull request by zaqqwerty**
Recently did a fresh source build after the update to TF 2.3.0 and Bazel 3.1.0, used what I learned to update the install instructions

### CODE REVIEW

**Comment by balopat** [comment]
FWIW, this worked for me, thank you, @zaqqwerty, I was running into all sorts of issues with the combination of tools that are in the current version of docs.

**Comment by MichaelBroughton** [comment]
If we are going to gear up for a 0.4 release in a week or two, would you mind updating this PR to check for any remaining old references ?

**Review by peezoslug — APPROVED** [review]

**Review by peezoslug — APPROVED** [review]

**Review by peezoslug — APPROVED** [review]

**Review by peezoslug — APPROVED** [review]

**Review by peezoslug — DISMISSED** [review]

**Comment by zaqqwerty** [comment]
@MichaelBroughton added #395 so we can update the research branch once this is in.

**Comment by MichaelBroughton** [comment]
Oops, we just fixed the workspace file, could we also update this to 2.3.1 now in anticipation of our cutting a 0.4 soon ?

**Comment by zaqqwerty** [comment]
Updated to 2.3.1

**Comment by MichaelBroughton** [comment]
Looking like we are almost ready to pull the trigger on 0.4.0 TFQ. One thing I noticed going through the notebooks was that

1. `PauliString.expectation_from_wavefunction` has been deprecated in favor of `PauliString.expectation_from_state_vector` and `TrialResult.final_state` has been deprecated in favor of `TrialResult.final_state_vector`. The calculate gradients tutorial and the hello many worlds tutorial both raise warnings on this. Would you mind updating this in the PR to move to the new names ?

I've checked all the tutorials and they seem to function on the latest `tfq-nightly` so I think after we fix these deprecation warnings we can merge this PR and #395 Either Tomorrow or the day after and then cut the release :tada:

**Comment by zaqqwerty** [comment]
Addressing the Cirq deprecations in #403

**Review by MichaelBroughton — APPROVED** [review]

**Pull request merged**
