### PR TITLE
Upgrade TF version from 2.7 to 2.11

### PR DESCRIPTION
**Pull request by jaeyoo**
1. Bump up the version of Bazel / Eigen / TensorFlow / google-protobuf.
2. Fix the issues related to numpy data types, TF status
3. Fix the compilation options with ABI breakage and std c++17
4. Fix some tests or ignore some tests not urgent
5. Update docs and notebooks

### CODE REVIEW

**Comment by jaeyoo** [comment]
Still have issues about tf.Variable in tf.while_loop, which blocks two optimizer tests failed. Let me figure out the culprit.

**Comment by jaeyoo** [comment]
Issues are all gone, just need to fix the errors coming from version mismatch in the notebook files

**Comment by jaeyoo** [comment]
All tests are fixed. This PR will resolve the following PRs together automatically:

https://github.com/tensorflow/quantum/pull/728 : Bump tensorflow from 2.7.0 to 2.9.3
https://github.com/tensorflow/quantum/pull/740 : Force old version of numpy in noise.ipynb
https://github.com/tensorflow/quantum/pull/719 : Replace tensorflow::Status::OK() with tensorflow::{Status, OkStatus}().
https://github.com/tensorflow/quantum/pull/717 : Bump protobuf from 3.17.3 to 3.18.3
https://github.com/tensorflow/quantum/pull/716 : Bump protobuf from 3.17.3 to 3.18.3 in /release
https://github.com/tensorflow/quantum/pull/694 : Bump numpy from 1.19.5 to 1.22.0

**Review by MichaelBroughton — APPROVED** [review]
LGTM

**Pull request merged**
