### PR TITLE
Update install.md

### PR DESCRIPTION
**Pull request by jaeyoo**
Upgrade tf version to 2.4.1

### CODE REVIEW

**Comment by MichaelBroughton** [comment]
This looks good! Let's merge this in right before we cut a new 0.5.0 release. If we merge it now the instructions would get updated immediately which we don't want.

**Comment by jaeyoo** [comment]
Sure! let's defer it to the new release day.

**Comment by MichaelBroughton** [comment]
When we release, lets also remember to update the examples in the `research` branch to use 2.4.1. Too (a seperate PR, but not urgent at all).

**Comment by MichaelBroughton** [comment]
In light of #482 maybe we should convert this PR to say that currently the latest install from pip is 2.3.1, but that the latest source build version is 2.4.1. What do you think ?

**Comment by MichaelBroughton** [comment]
We've gone and cut the 0.5.0 release with updated install instructions so we can close this for now.

**Pull request closed without merging**
