### PR TITLE
y_train_hinge must be paired with y_train_nocon

### PR DESCRIPTION
**Pull request by tiancheng2000**
`y_train_hinge`, as labels, must be accordance with `x_train_tfcirc`, which originated from `x_train_nocon`.
Otherwise there will be lots of mismatches between `xs` and `ys` on training.

### CODE REVIEW

**Comment by tiancheng2000** [comment]
@googlebot I signed it!

**Comment by MichaelBroughton** [comment]
Gentle reminder @MarkDaoust

**Comment by MarkDaoust** [comment]
@MichaelBroughton

I had to pin cirq==0.7 to make this work, otherwise (cirq==0.8) import `tfq` fails with 

```
/usr/local/lib/python3.6/dist-packages/tensorflow_quantum/core/serialize/serializer.py in _eigen_gate_serializer(gate_type, serialized_id)
    112             serialized_name="exponent",
    113             serialized_type=float,
--> 114             gate_getter=lambda x: _symbol_extractor(x.exponent)),
    115         cirq.google.SerializingArg(
    116             serialized_name="exponent_scalar",

TypeError: __init__() got an unexpected keyword argument 'gate_getter'
```

**Comment by MarkDaoust** [comment]
This change looks correct to me, I'm not sure how it got out of sync, but I'm running it once to confirm that everything works.

**Pull request merged**
