### PR TITLE
Visualization tutorial

### PR DESCRIPTION
**Pull request by MichaelBroughton**
Adds a TensorBoard visualization tutorial that showcases basic integration functionality and encourages users to experiment on their own. Would appreciate a thorough review from both @zaqqwerty and @lamberta .

### CODE REVIEW

**Review by zaqqwerty — CHANGES_REQUESTED** [review]
(see ReviewNB comments)

**Review by bileschi — DISMISSED** [review]
This broadly looks good to me.  By the way.  Reviewing notebooks in github is easier with https://www.reviewnb.com/.   We use it in TensorBoard.

**Comment by lamberta** [comment]
For images, I would start to organize them in directories with the same name as the tutorial: `docs/tutorials/images/<tutorial-name>/` —for this tutorial and possibly the others in a follow-up PR. As you collect more tutorial images this will become difficult to maintain.

**Comment by lamberta** [comment]
Run through [nbfmt](https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/tools/) to make sure the TOC is set, etc:

```
$ python3 -m pip install -U --user git+https://github.com/tensorflow/docs

$ python3 -m tensorflow_docs.tools.nbfmt notebook.ipynb
```

**Review by lamberta — APPROVED** [review]
Looks cool!
Discussed in chat and will organize image files in another PR

**Pull request merged**
