### PR TITLE
Upgrade to TF2.5.1

### PR DESCRIPTION
**Pull request by jaeyoo**

### CODE REVIEW

**Comment by jaeyoo** [comment]
https://github.com/tensorflow/quantum/issues/583

**Comment by jaeyoo** [comment]
Just quick question - should I upgrade our TFQ version too?

**Comment by MichaelBroughton** [comment]
Nope, it's not worth upgrading the TFQ version yet :). Don't forget to update the install instructions for the development version of TFQ. Also, did you experiment with the performance at all ?

**Review by MichaelBroughton — DISMISSED** [review]
LGTM

**Review by MichaelBroughton — APPROVED** [review]
LGTM

**Pull request merged**
